logging:
  file:
    name: flight-booking.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
spring:
  application:
    name: Flight_Application
  datasource:
    password: pass@word1
    url: jdbc:mysql://localhost:3306/flightapp
    username: root
   #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
jwt:
  secret: access**access
